# Generated by Django 3.1.3 on 2023-05-14 09:03

import ckeditor_uploader.fields
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import market.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=300, verbose_name='last name')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='username')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='mobile number')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='email')),
                ('nationalcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='national code')),
                ('address', models.JSONField(blank=True, null=True, verbose_name='آدرس')),
                ('active', models.BooleanField(default=True, verbose_name='وضعیت فعالیت')),
                ('superuser', models.BooleanField(default=False, verbose_name='وضعیت مدیریت')),
                ('staff', models.BooleanField(default=False, verbose_name='وضعیت کارمندی')),
                ('citypercode', models.CharField(blank=True, max_length=3, null=True, verbose_name='پیش شماره')),
                ('phone', models.CharField(blank=True, max_length=8, verbose_name='شماره تلفن ثابت')),
                ('birthday', django_jalali.db.models.jDateField(null=True, verbose_name='تاریخ تولد')),
                ('comment_list', models.JSONField(blank=True, null=True, verbose_name='لیست نظرات ها')),
                ('factor_list', models.JSONField(blank=True, null=True, verbose_name='لیست فاکتور ها')),
                ('message_list', models.JSONField(blank=True, null=True, verbose_name='لیست پیام ها')),
                ('favorite_list', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(verbose_name='محصول مورد علاقه'), blank=True, null=True, size=None, verbose_name='لیست محصولات مورد علاقه')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ('id', 'createdate'),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('mobilenumber', models.CharField(blank=True, max_length=11, verbose_name='شماره موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'بررسی نشده است'), (1, 'در حال بررسی'), (2, 'بسته شده است')], default=0, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'ارتباط با ما',
                'verbose_name_plural': 'ارتباط با ما ها',
                'ordering': ('id', 'createdate'),
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/mobile/', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'گالری',
                'verbose_name_plural': 'گالری ها',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=225, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن')),
                ('users', models.JSONField(blank=True, null=True, verbose_name='کاربران')),
                ('datetime', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ثبت')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images/slider/', verbose_name='عکس')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='برچسب روی اسلایدر')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک')),
                ('publish', models.BooleanField(choices=[(True, 'منتشر شده'), (False, 'منتشر نشده')], default=True, verbose_name='وضعیت انتشار')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر ها',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=225, verbose_name='نام')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='شناسه')),
                ('brand', models.CharField(max_length=50, verbose_name='برند')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='بررسی تخصصی')),
                ('index_image', models.ImageField(blank=True, null=True, upload_to='media/images/mobile/', verbose_name='عکس اصلی')),
                ('points', models.JSONField(blank=True, null=True, verbose_name='امتیازات')),
                ('price', models.CharField(max_length=15, verbose_name='قیمت')),
                ('discount', models.CharField(default='0', max_length=15, verbose_name='تخفیف')),
                ('comments', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(verbose_name='نظر'), blank=True, null=True, size=None, verbose_name='نظرات')),
                ('colors', models.JSONField(blank=True, null=True, verbose_name='رنگ ها')),
                ('inventory', models.IntegerField(default=1, verbose_name='موجودی')),
                ('guarantees', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=225, verbose_name='گارانتی'), blank=True, null=True, size=None, verbose_name='گارانتی ها')),
                ('technical_details', models.JSONField(blank=True, null=True, verbose_name='جزئیات فنی')),
                ('datecreate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بارگذاری')),
                ('dateupdate', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('publish', models.BooleanField(choices=[(True, 'منتشر شده'), (False, 'در انتظار تایید')], default=False, verbose_name='وضعیت انتشار')),
                ('gallery', models.ManyToManyField(blank=True, related_name='mobile_gallery', to='market.Gallery', verbose_name='گالری ها')),
            ],
            options={
                'verbose_name': 'موبایل',
                'verbose_name_plural': 'موبایل ها',
                'ordering': ('id', 'datecreate'),
            },
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=market.models.factor_number(5), max_length=5, unique=True, verbose_name='شماره فاکتور')),
                ('address', models.JSONField(blank=True, null=True, verbose_name='آدرس')),
                ('items', models.JSONField(blank=True, null=True, verbose_name='محصولات')),
                ('post_price', models.CharField(default='0', max_length=15, verbose_name='هزینه پست')),
                ('total_price', models.CharField(default='0', max_length=15, verbose_name='هزینه کل')),
                ('payment_status', models.BooleanField(choices=[(True, 'پرداخت شد'), (False, 'پرداخت نشده')], default=False, verbose_name='وضعیت پرداخت')),
                ('orderdate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ثبت')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'فاکتور پرداخت نشده است'), (1, 'فاکتور در حال آماده سازی'), (2, 'سفارش آماده است'), (3, 'سفارش ارسال شده است'), (4, 'فاکتور لغو شده است')], default=0, verbose_name='وضعیت فاکتور')),
                ('FK_User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_factor', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتور ها',
                'ordering': ('id', 'orderdate'),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('likes', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(verbose_name='لایک'), blank=True, null=True, size=None, verbose_name='لایک ها')),
                ('replay', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(verbose_name='لایک'), blank=True, null=True, size=None, verbose_name='ریپلای ها')),
                ('datecreate', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('FK_User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_comment', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ('id', 'datecreate'),
            },
        ),
    ]
