# Generated by Django 3.1.3 on 2022-01-24 14:07

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import market.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='username')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=300, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('mobile', models.CharField(max_length=11, null=True, verbose_name='شماره موبایل')),
                ('state', models.CharField(max_length=50, null=True, verbose_name='استان')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='شهر')),
                ('zipcode', models.CharField(max_length=10, null=True, verbose_name='کدپستی')),
                ('address', models.TextField(null=True, verbose_name='آدرس')),
                ('active', models.BooleanField(default=True, verbose_name='وضعیت فعالیت')),
                ('superuser', models.BooleanField(default=False, verbose_name='وضعیت مدیریت')),
                ('staff', models.BooleanField(default=False, verbose_name='وضعیت کارمندی')),
                ('favorite_list', models.JSONField(default=market.models.default_json_field(), verbose_name='لیست علاقه مندی ها')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ('id', 'create_date'),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن')),
                ('mobile', models.CharField(max_length=11, null=True, verbose_name='شماره موبایل')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='ایمیل')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'بررسی نشده است'), (1, 'در حال بررسی'), (2, 'بسته شده است')], default=0, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'ارتباط با ما',
                'verbose_name_plural': 'ارتباط با ما ها',
                'ordering': ('id', 'create_date'),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن')),
                ('users', models.JSONField(default=market.models.default_json_field(), verbose_name='کاربران')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
                'ordering': ('id', 'create_date'),
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='شناسه')),
                ('brand', models.CharField(max_length=50, verbose_name='برند')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='بررسی تخصصی')),
                ('index_image', models.ImageField(upload_to='media/images/mobile/', verbose_name='عکس اصلی')),
                ('gallery', models.JSONField(default=market.models.default_json_field(), verbose_name='گالری')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='تخفیف')),
                ('technical_details', models.JSONField(default=market.models.default_json_field(), verbose_name='جزئیات فنی')),
                ('guarantees', models.JSONField(default=market.models.default_json_field(), verbose_name='گارانتی')),
                ('points', models.JSONField(default=market.models.default_json_field(), verbose_name='امتیازات')),
                ('colors', models.JSONField(default=market.models.default_json_field(), verbose_name='رنگ ها')),
                ('publish', models.BooleanField(default=True, verbose_name='وضعیت انتشار')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بارگذاری')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'موبایل',
                'verbose_name_plural': 'موبایل ها',
                'ordering': ('id', 'create_date'),
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images/slider/', verbose_name='عکس')),
                ('description', models.CharField(max_length=50, null=True, verbose_name='برچسب روی اسلایدر')),
                ('link', models.URLField(null=True, verbose_name='لینک')),
                ('publish', models.BooleanField(default=True, verbose_name='وضعیت انتشار')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر ها',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='کد')),
                ('address', models.JSONField(default=market.models.default_address_field(), verbose_name='آدرس')),
                ('items', models.JSONField(default=market.models.default_json_field(), verbose_name='محصولات')),
                ('post_price', models.PositiveIntegerField(default=0, verbose_name='هزینه پست')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='هزینه کل')),
                ('payment_status', models.BooleanField(choices=[(True, 'پرداخت شد'), (False, 'پرداخت نشده')], default=False, verbose_name='وضعیت پرداخت')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'فاکتور پرداخت نشده است'), (1, 'فاکتور در حال آماده سازی'), (2, 'سفارش آماده است'), (3, 'سفارش ارسال شده است'), (4, 'فاکتور لغو شده است')], default=0, verbose_name='وضعیت فاکتور')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان سفارش')),
                ('fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_factor', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتور ها',
                'ordering': ('id', 'order_date'),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن')),
                ('likes', models.JSONField(default=market.models.default_json_field(), verbose_name='لایک')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('fk_mobile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_comment', to='market.mobile', verbose_name='موبایل')),
                ('fk_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_replay', to='market.comment', verbose_name='کامنت پدر')),
                ('fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_comment', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ('id', 'create_date'),
            },
        ),
    ]
