# Generated by Django 3.1.3 on 2021-01-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=300, verbose_name='last name')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='username')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='mobile number')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='email')),
                ('nationalcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='national code')),
                ('address', models.JSONField(blank=True, null=True, verbose_name='آدرس')),
                ('active', models.BooleanField(default=True, verbose_name='وضعیت فعالیت')),
                ('superuser', models.BooleanField(default=False, verbose_name='وضعیت مدیریت')),
                ('staff', models.BooleanField(default=False, verbose_name='وضعیت کارمندی')),
                ('author', models.BooleanField(default=False, verbose_name='وضعیت نویسندگی')),
                ('citypercode', models.CharField(blank=True, max_length=3, null=True, verbose_name='پیش شماره')),
                ('phone', models.CharField(blank=True, max_length=8, verbose_name='شماره تلفن ثابت')),
                ('brithday', models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ تولد')),
                ('comment_list', models.JSONField(blank=True, null=True, verbose_name='لیست نظرات ها')),
                ('factor_list', models.JSONField(blank=True, null=True, verbose_name='لیست فاکتور ها')),
                ('message_list', models.JSONField(blank=True, null=True, verbose_name='لیست پیام ها')),
                ('favorite_list', models.JSONField(blank=True, null=True, verbose_name='لیست موقعیت های مورد علاقه')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ('id', 'createdate'),
            },
        ),
    ]
