# Generated by Django 3.1.3 on 2021-01-09 13:24

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('likes', models.JSONField(blank=True, null=True, verbose_name='لایک ها')),
                ('replay', models.JSONField(blank=True, null=True, verbose_name='ریپلای ها')),
                ('datecreate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('status', models.BooleanField(choices=[(True, 'خوانده شده'), (False, 'خوانده نشده')], default=False, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ('id', 'datecreate'),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('mobilenumber', models.CharField(blank=True, max_length=11, verbose_name='شماره موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'بررسی نشده است'), (1, 'در حال بررسی'), (2, 'بسته شده است')], default=0, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'ارتباط با ما',
                'verbose_name_plural': 'ارتباط با ما ها',
                'ordering': ('id', 'createdate'),
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='author',
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=225, verbose_name='نام')),
                ('slug', models.SlugField(unique=True, verbose_name='شناسه')),
                ('brand', models.CharField(max_length=50, verbose_name='برند')),
                ('description', models.TextField(blank=True, null=True, verbose_name='بررسی تخصصی')),
                ('index_image', models.ImageField(blank=True, null=True, upload_to='media/images/mobile/', verbose_name='عکس اصلی')),
                ('gallery', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='media/images/mobile/', verbose_name='عکس'), blank=True, null=True, size=None, verbose_name='گالری')),
                ('points', models.JSONField(blank=True, null=True, verbose_name='امتیازات')),
                ('price', models.CharField(max_length=15, verbose_name='قیمت')),
                ('discount', models.PositiveSmallIntegerField(default=0, verbose_name='تخفیف')),
                ('colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=9, verbose_name='رنگ'), blank=True, null=True, size=None, verbose_name='رنگ ها')),
                ('inventory', models.IntegerField(default=1, verbose_name='موجودی')),
                ('guarantees', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=225, verbose_name='گارانتی'), blank=True, null=True, size=None, verbose_name='گارانتی ها')),
                ('technical_details', models.JSONField(blank=True, null=True, verbose_name='جزئیات فنی')),
                ('datecreate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بارگذاری')),
                ('dateupdate', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('publish', models.BooleanField(choices=[(True, 'منتشر شده'), (False, 'در انتظار تایید')], default=False, verbose_name='وضعیت انتشار')),
                ('FK_Comments', models.ManyToManyField(blank=True, related_name='mobile_comments', to='market.Comment', verbose_name='نظرات')),
            ],
            options={
                'verbose_name': 'موبایل',
                'verbose_name_plural': 'موبایل ها',
                'ordering': ('id', 'datecreate'),
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='FK_User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_comment', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
