# Generated by Django 3.1.3 on 2021-01-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20210114_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='discount',
            field=models.CharField(default='0', max_length=15, verbose_name='تخفیف'),
        ),
    ]
