# Generated by Django 3.1.3 on 2021-01-14 18:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20210114_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='بررسی تخصصی'),
        ),
    ]
