# Generated by Django 3.1.3 on 2021-01-14 19:46

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20210114_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ثبت'),
        ),
    ]
