# Generated by Django 3.1.3 on 2021-01-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_mobile_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='عنوان'),
        ),
    ]
