# Generated by Django 3.1.3 on 2021-01-15 02:58

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20210115_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datecreate',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
    ]
