# Generated by Django 3.1.3 on 2021-01-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20210115_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='replay',
        ),
    ]
