# Generated by Django 3.1.3 on 2021-01-15 13:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20210115_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(verbose_name='لایک'), blank=True, null=True, size=None, verbose_name='لایک ها'),
        ),
        migrations.AddField(
            model_name='comment',
            name='replay',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(verbose_name='لایک'), blank=True, null=True, size=None, verbose_name='ریپلای ها'),
        ),
    ]
