# Generated by Django 3.1.3 on 2021-01-15 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_auto_20210115_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='colors',
        ),
    ]
