# Generated by Django 3.1.3 on 2021-01-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_remove_mobile_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='colors',
            field=models.JSONField(blank=True, null=True, verbose_name='رنگ ها'),
        ),
    ]
