# Generated by Django 3.1.3 on 2021-01-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_remove_comment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='post_price',
            field=models.CharField(default='0', max_length=15, verbose_name='هزینه پست'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='total_price',
            field=models.CharField(default='0', max_length=15, verbose_name='هزینه کل'),
        ),
    ]
