# Generated by Django 3.1.3 on 2021-01-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_auto_20210118_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'فاکتور پرداخت نشده است'), (1, 'فاکتور در حال آماده سازی'), (2, 'سفارش آماده است'), (3, 'سفارش ارسال شده است'), (4, 'فاکتور لغو شده است')], default=0, verbose_name='وضعیت فاکتور'),
        ),
    ]
