# Generated by Django 3.1.3 on 2021-01-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_remove_mobile_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/mobile/', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'گالری',
                'verbose_name_plural': 'گالری ها',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='mobile',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='mobile_gallery', to='market.Gallery', verbose_name='گالری ها'),
        ),
    ]
