# Generated by Django 3.1.3 on 2022-01-24 14:07

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import market.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='شناسه')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن')),
                ('index_image', models.ImageField(upload_to='media/images/blog/', verbose_name='عکس اصلی')),
                ('slider_image', models.ImageField(upload_to='media/images/blog/', verbose_name='عکس اسلایدر')),
                ('points', models.JSONField(default=market.models.default_json_field(), verbose_name='امتیازات')),
                ('publish', models.BooleanField(default=True, verbose_name='وضعیت انتشار')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
                'ordering': ('id', 'create_date'),
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن')),
                ('likes', models.JSONField(default=market.models.default_json_field(), verbose_name='لایک')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('fk_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_comment_replay', to='blog.postcomment', verbose_name='کامنت پدر')),
                ('fk_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_comment', to='blog.post', verbose_name='پست')),
                ('fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_post_comment', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر پست',
                'verbose_name_plural': 'نظرات پست',
                'ordering': ('id', 'create_date'),
            },
        ),
    ]
