# Generated by Django 3.1.3 on 2023-05-14 09:03

import ckeditor_uploader.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='شناسه')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='متن')),
                ('index_image', models.ImageField(blank=True, null=True, upload_to='media/images/blog/', verbose_name='عکس اصلی')),
                ('slider_image', models.ImageField(blank=True, null=True, upload_to='media/images/blog/', verbose_name='عکس اسلایدر')),
                ('points', models.JSONField(blank=True, null=True, verbose_name='امتیازات')),
                ('comments', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(verbose_name='نظر'), blank=True, null=True, size=None, verbose_name='نظرات')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updatedate', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('publishdate', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('publish', models.BooleanField(choices=[(True, 'منتشر شده'), (False, 'منتشر نشده')], default=False, verbose_name='وضعیت انتشار')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
                'ordering': ('id', 'createdate', 'publishdate'),
            },
        ),
    ]
