# Generated by Django 3.1.3 on 2021-01-16 14:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(verbose_name='نظر'), blank=True, null=True, size=None, verbose_name='نظرات'),
        ),
    ]
