# Generated by Django 3.1.3 on 2021-01-18 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
    ]
